### ISSUE TITLE
Todo-20160313

### ISSUE THREAD

**Issue by chlorella** [chlorella/fyp-BA#3]
- [x] Get json Caption/Test and act as alart
^ Json
- [x] Use Camera as take a photo option
- [x] Use Camera as main activity(touch to switch) 
(Merge function/ switch to get different result)
^ Camera2 API
- [x]  Color Picker
^ CameraColorPicker
